{% set name = "pywinpty" %}
{% set version = "0.5.0" %}
{% set hash = "487b785c491332b4110b41db21d8f3850e40a3ca2035a838a95b8087036f782a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/spyder-ide/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  skip: True  # [not (win and py3k)]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - cython
    - python
    - setuptools
    - winpty
  run:
    - python
    - winpty

test:
  imports:
    - winpty

about:
  home: https://github.com/spyder-ide/pywinpty
  license: MIT
  summary: 'Python bindings for the winpty library'
  description: |
    Python bindings for the winpty pseudo terminal library.
    It allows to create and communicate with Windows processes that print outputs
     and recieve inputs via console input and output pipes.
  doc_url: https://github.com/spyder-ide/pywinpty
  dev_url: https://github.com/spyder-ide/pywinpty

extra:
  recipe-maintainers:
    - ccordoba12
    - andfoy
    - goanpeca
