{% set version = "2.0.15" %}

package:
  name: pywinpty
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pywinpty/pywinpty-{{ version }}.tar.gz
  sha256: 312cf39153a8736c617d45ce8b6ad6cd2107de121df91c455b10ce6bba7a39b2

build:
  number: 0
  skip: true  # [not win]
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - clang
    - llvm
    - rust
    - llvmdev
    - llvm-tools
    - libclang
    - maturin <=0.12.0
    - toml
    - pip
    - winpty
  host:
    - python
    - pip
    - winpty
  run:
    - python
    - winpty

test:
  imports:
    - winpty

about:
  home: https://github.com/spyder-ide/pywinpty
  license: MIT
  license_file: LICENSE.txt
  summary: Pseudoterminals for Windows in Python
  description: |
    PyWinpty allows creating and communicating with Windows processes that
    receive input and print outputs via console input and output pipes.
    PyWinpty supports both the native ConPTY interface and the previous,
    fallback winpty library.
  doc_url: https://github.com/spyder-ide/pywinpty
  dev_url: https://github.com/spyder-ide/pywinpty

extra:
  recipe-maintainers:
    - blink1073
    - ccordoba12
    - andfoy
    - ocefpaf
