{% set version = "1.1.5" %}

package:
  name: pywinpty
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pywinpty/pywinpty-{{ version }}.tar.gz
  sha256: 92125f0f8e4e64bb5f3bf270a182c9206dc1765542c59bc07441908a9db17504

build:
  number: 1
  skip: true  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang
    - llvm
    - rust
    - llvmdev
    - llvm-tools
    - libclang
    - maturin <=0.12.0
    - toml
    - pip
    - winpty
  host:
    - python
    - pip
    - winpty
  run:
    - python
    - winpty

test:
  imports:
    - winpty

about:
  home: https://github.com/spyder-ide/pywinpty
  license: MIT
  license_file: LICENSE.txt
  summary: Pseudoterminals for Windows in Python
  description: |
    PyWinpty allows creating and communicating with Windows processes that
    receive input and print outputs via console input and output pipes.
    PyWinpty supports both the native ConPTY interface and the previous,
    fallback winpty library.
  doc_url: https://github.com/spyder-ide/pywinpty
  dev_url: https://github.com/spyder-ide/pywinpty

extra:
  recipe-maintainers:
    - blink1073
    - ccordoba12
    - andfoy
    - ocefpaf
