{% set version = "2.0.8" %}

package:
  name: pywinpty
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pywinpty/pywinpty-{{ version }}.tar.gz
  sha256: a89b9021c63ef78b1e7d8e14f0fac4748c88a0c2e4f529c84f37f6e72b914280

build:
  number: 1
  skip: true  # [not win]
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang
    - llvm
    - rust
    - llvmdev
    - llvm-tools
    - libclang
    - maturin <=0.12.0
    - toml
    - pip
    - winpty
  host:
    - python
    - pip
    - winpty
  run:
    - python
    - winpty

test:
  imports:
    - winpty

about:
  home: https://github.com/spyder-ide/pywinpty
  license: MIT
  license_file: LICENSE.txt
  summary: Pseudoterminals for Windows in Python
  description: |
    PyWinpty allows creating and communicating with Windows processes that
    receive input and print outputs via console input and output pipes.
    PyWinpty supports both the native ConPTY interface and the previous,
    fallback winpty library.
  doc_url: https://github.com/spyder-ide/pywinpty
  dev_url: https://github.com/spyder-ide/pywinpty

extra:
  recipe-maintainers:
    - blink1073
    - ccordoba12
    - andfoy
    - ocefpaf
