{% set version = "2.0.5" %}

package:
  name: pywinpty
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pywinpty/pywinpty-{{ version }}.tar.gz
  sha256: e125d3f1804d8804952b13e33604ad2ca8b9b2cac92b27b521c005d1604794f8

build:
  number: 1
  skip: true  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang
    - llvm
    - rust
    - llvmdev
    - llvm-tools
    - libclang
    - maturin <=0.12.0
    - toml
    - pip
    - winpty
  host:
    - python
    - pip
    - winpty
  run:
    - python
    - winpty

test:
  imports:
    - winpty

about:
  home: https://github.com/spyder-ide/pywinpty
  license: MIT
  license_file: LICENSE.txt
  summary: Pseudoterminals for Windows in Python
  description: |
    PyWinpty allows creating and communicating with Windows processes that
    receive input and print outputs via console input and output pipes.
    PyWinpty supports both the native ConPTY interface and the previous,
    fallback winpty library.
  doc_url: https://github.com/spyder-ide/pywinpty
  dev_url: https://github.com/spyder-ide/pywinpty

extra:
  recipe-maintainers:
    - blink1073
    - ccordoba12
    - andfoy
    - ocefpaf
