appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dLDZqPVWzcaOeli/sxeffg+NEiu4OoYcemhDd2ocfUHagpBlGjCgZyFSD5+0kjkodHSJSGDvFuBiYzaaaXnDW60NkQCaoqzfz0RW4r0dDsnZQ48L4JB18P0OLValtwj3gSaua+OWlVzgK3ozGm5acFmxqxddyXKEVt4jR7yVyg7vV3yIBZB08Ln1w+aLwfEtcXvqIbwncVcPiQKoiKIrTb1mMXpd1x+Ve6ZnY+gybctbdtw8g54egzIG0ObaXYdIDwCPGji1TqVTSnU7urvOspxdbrIxKxNCyowrLgSCig0hmo0TqoouW+xEvppUGM43xWM28+JeS/oQ/UDqF36L3bL5c0ADP1wD5OJ91lvRJwwEDmZfafQUNhVlUjXQ0+giRiOTNj5wuy7Yb+C0bxE9QWfI3e0Bb/xaOdNIP9oOWZAwJqOY+6vnSB+9vTHxOVQg9l5F4KkKRfURVaDawxYSsW4jgAwJrGitOj50NniTrAYwsWVkJXvNe7zdR578153qDk+ujL+orHFKKkJ5PxsSOAv6mel/BQZwRyRYoUQiINkm6fYkT4bRZJ/Z/wR2RbdhX8BuQKyPtL9qH0e62nAljuVDKLh85a/Gl/JQs7dHy7OFfb7PStZQE7hCX6I54MIACD7WNjkzDxfIjHRQa67r9ezyJO7LuAZXWh0okjgER2w=}
conda_forge_output_validation: true
